# Generated by Django 5.1.1 on 2024-10-12 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationinvitation",
            old_name="org",
            new_name="organization",
        ),
        migrations.RenameField(
            model_name="organizationmember",
            old_name="org",
            new_name="organization",
        ),
    ]
