# Generated by Django 5.1.1 on 2024-10-12 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0002_rename_org_organizationinvitation_organization_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationInvitation",
            new_name="Invitation",
        ),
        migrations.RenameModel(
            old_name="OrganizationMember",
            new_name="Member",
        ),
    ]
