# Generated by Django 5.1.1 on 2024-10-12 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_rename_organizationinvitation_invitation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitation",
            options={
                "ordering": ["-id"],
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "member", "verbose_name_plural": "members"},
        ),
        migrations.AlterModelTable(
            name="invitation",
            table="invitations",
        ),
        migrations.AlterModelTable(
            name="member",
            table="members",
        ),
    ]
