# Generated by Django 5.1.1 on 2024-10-12 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-id",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
